Petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Petstagram.common.urls')),
    path('accounts/', include('Petstagram.accounts.urls')),
    path('pets/', include('Petstagram.pets.urls')),
    path('photos/', include('Petstagram.photos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Petstagram/common/models.py
from django.db import models

from Petstagram.photos.models import PetPhoto


# Create your models here.
class PhotoComment(models.Model):
    MAX_TEXT_LENGTH = 30

    text = models.TextField(max_length=MAX_TEXT_LENGTH)

    created_at = models.DateTimeField(
        auto_now_add=True,  # done only on 'create'
    )
    modified_at = models.DateTimeField(
        auto_now=True,  # on every save
    )

    pet_photo = models.ForeignKey(
        PetPhoto,
        on_delete=models.DO_NOTHING
    )

class PhotoLike(models.Model):
    pet_photo = models.ForeignKey(
        PetPhoto,
        on_delete=models.DO_NOTHING
    )

# photo_like = PhotoLike.objects.filter(pet_photo_id=pet_photo.pk, user=request.user)

templates/partials/pet_photo_list.html
{% load static %}
{%  for photo in photo_list %}
    {% include 'partials/pet_photo_list_item.html' with photo=photo%}
{% empty %}
    <img class="no-posts" src='{% static "images/no_posts.png"%}' alt="no posts image">
{% endfor %}

templates/partials/pet_photo_list_item.html
{% load static %}
<div class="card">

                <div class="top">
                    <div class="userDetails">
                        <a href="{% url 'details profile' pk=1%}">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <img src='{% static "images/person.png"%}' alt="img8">
                                    </div>
                                </div>
                            </div>
                        </a>
                        <h3>
                            <a href="{% url 'details profile' pk=1%}">
                                Diyan Kalaydzhiev
                  
                            </a>
                            <br>
                            <span>
                                {{ pet_photo.location }}
                            </span>
                        </h3>
                    </div>
                </div>

                <div class="imgBx" id="photo-{{ photo.pk }}">
                    <img src='{{ photo.photo.url }}' alt="post" class="cover">
                </div>
     
                <div class="bottom">
                    <div class="actionBtns">
                        <div class="left">
                            <span class="heart">
                                <a href="{% url 'like_pet_photo' pk=photo.pk %}">
                                    {% if photo.photolike_set.count > 0 %}
                                    <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                                    {% else %}
                                    <i class="fa-regular fa-heart"></i>
                                    {% endif %}
                                </a>
                            </span>

                            <a href="#">
                                <i class="fa-solid fa-share"></i>
                            </a>

                        </div>
                    </div>

                    <p class="likes">{{ photo.photolike_set.count }} likes</p>
                    
                    {% for pet in photo.pets.all %}
                    <a href="{% url 'details pet' username='Veronika' pet_slug=pet.slug%}">
                        <p class="message">
                            <b>{{ pet.name }}</b>
                        </p>
                    </a>
                    {% endfor %}

                    <a href="{% url 'details photo' pk=photo.pk %}">
                        <h4 class="details">See details</h4>
                    </a>

                    <h5 class="postTime">{{ photo.created_at|date:'d/m/Y' }}</h5>


                    <div class="addComments">

                        <form method="post" action="#">
                            <label for="id_body">Body:</label>
                            <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                                      required="" id="id_body"></textarea>
                            <button type="submit">Post</button>
                        </form>


                    </div>

                </div>
            </div>